package com.skyla.pos.ui.theme

import androidx.compose.ui.graphics.Color

// Primary - Sky Blue
val SkyBlue = Color(0xFF87CEEB)
val SkyBlueDark = Color(0xFF5BA3C9)
val SkyBlueLight = Color(0xFFB6E3F4)
val SkyBlueContainer = Color(0xFFE1F5FE)

// Light Theme Colors
val md_theme_light_primary = Color(0xFF0077B6)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFCAE6FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001E30)
val md_theme_light_secondary = Color(0xFF4FC3F7)
val md_theme_light_onSecondary = Color(0xFF003547)
val md_theme_light_secondaryContainer = Color(0xFFB3E5FC)
val md_theme_light_onSecondaryContainer = Color(0xFF001F2A)
val md_theme_light_tertiary = Color(0xFF00BCD4)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFB2EBF2)
val md_theme_light_onTertiaryContainer = Color(0xFF002022)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFF8FDFF)
val md_theme_light_onBackground = Color(0xFF001F2A)
val md_theme_light_surface = Color(0xFFF8FDFF)
val md_theme_light_onSurface = Color(0xFF001F2A)
val md_theme_light_surfaceVariant = Color(0xFFDCE4EB)
val md_theme_light_onSurfaceVariant = Color(0xFF41484D)
val md_theme_light_outline = Color(0xFF71787E)
val md_theme_light_outlineVariant = Color(0xFFC0C8CF)

// Dark Theme Colors
val md_theme_dark_primary = Color(0xFF80D8FF)
val md_theme_dark_onPrimary = Color(0xFF00344F)
val md_theme_dark_primaryContainer = Color(0xFF004B71)
val md_theme_dark_onPrimaryContainer = Color(0xFFCAE6FF)
val md_theme_dark_secondary = Color(0xFF81D4FA)
val md_theme_dark_onSecondary = Color(0xFF003548)
val md_theme_dark_secondaryContainer = Color(0xFF004D67)
val md_theme_dark_onSecondaryContainer = Color(0xFFB3E5FC)
val md_theme_dark_tertiary = Color(0xFF4DD0E1)
val md_theme_dark_onTertiary = Color(0xFF003739)
val md_theme_dark_tertiaryContainer = Color(0xFF004F52)
val md_theme_dark_onTertiaryContainer = Color(0xFFB2EBF2)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF001F2A)
val md_theme_dark_onBackground = Color(0xFFBFE9FF)
val md_theme_dark_surface = Color(0xFF001F2A)
val md_theme_dark_onSurface = Color(0xFFBFE9FF)
val md_theme_dark_surfaceVariant = Color(0xFF41484D)
val md_theme_dark_onSurfaceVariant = Color(0xFFC0C8CF)
val md_theme_dark_outline = Color(0xFF8B9298)
val md_theme_dark_outlineVariant = Color(0xFF41484D)

// Status Colors
val StatusSuccess = Color(0xFF2E7D32)
val StatusWarning = Color(0xFFF57C00)
val StatusDraft = Color(0xFF757575)
val StatusVoided = Color(0xFFBA1A1A)
